name: release
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    name: Perform a semantic release
    runs-on: ubuntu-latest
    steps:
      - name: action-release
        uses: mateothegreat/action-release@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          owner: mateothegreat
          repo: action-release
          increment: patch
          release_name: MVP release ğŸ‰
          release_body: |
            This is the body of the release.
            Line 2 on and one ğŸ‘..
          release_notes: true
          committer_name: Matthew Davis
          committer_email: matthew@matthewdavis.io
